
/** Minimal styles */
export const styles: Record<string, React.CSSProperties> = {
    shell: {
      fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
      padding: 20,
      maxWidth: 1200,
      margin: "0 auto",
    },
    topBar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 16,
    },
    title: { fontSize: 18, fontWeight: 700 },
    h2: { margin: 0, fontSize: 22 },
    h3: { margin: 0, fontSize: 16 },
    p: { marginTop: 8, color: "#333", lineHeight: 1.4 },
    subtle: { color: "#666", fontSize: 13, marginTop: 4 },
    subtleSmall: { color: "#666", fontSize: 12 },
    row: { display: "flex", gap: 10, alignItems: "center" },
    rowBetween: { display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center" },
  
    grid: { display: "grid", gridTemplateColumns: "260px 1fr", gap: 18, alignItems: "start" },
    left: { borderRight: "1px solid #eee", paddingRight: 14 },
    right: {},
  
    btn: {
      border: "1px solid #111",
      background: "#111",
      color: "white",
      padding: "10px 12px",
      borderRadius: 10,
      cursor: "pointer",
      fontSize: 13,
      fontWeight: 600,
    },
    btnGhost: {
      border: "1px solid #ddd",
      background: "white",
      color: "#111",
      padding: "10px 12px",
      borderRadius: 10,
      cursor: "pointer",
      fontSize: 13,
      fontWeight: 600,
    },
    uploadLabel: { display: "inline-block" },
  
    pageList: { display: "grid", gap: 8, marginTop: 10 },
    pageBtn: {
      padding: "10px 12px",
      textAlign: "left",
      borderRadius: 10,
      border: "1px solid #ddd",
      background: "white",
      cursor: "pointer",
      fontWeight: 600,
    },
    pageBtnActive: {
      padding: "10px 12px",
      textAlign: "left",
      borderRadius: 10,
      border: "1px solid #111",
      background: "#f4f4f4",
      cursor: "pointer",
      fontWeight: 700,
    },
  
    notice: {
      background: "#fafafa",
      border: "1px solid #eee",
      padding: 10,
      borderRadius: 10,
      fontSize: 13,
      color: "#333",
    },
  
    workspaceRow: { display: "grid", gridTemplateColumns: "1fr 320px", gap: 14, alignItems: "start" },
    canvasWrap: {
      position: "relative",
      border: "1px solid #eee",
      borderRadius: 12,
      overflow: "hidden",
      background: "white",
    },
    canvas: { display: "block", width: "100%" },
    canvasOverlay: {
      position: "absolute",
      left: 0,
      top: 0,
      zIndex: 2,
      // size set inline to match canvas pixels
    },
    loadingCover: {
      position: "absolute",
      left: 0,
      top: 0,
      right: 0,
      bottom: 0,
      display: "grid",
      placeItems: "center",
      background: "rgba(255,255,255,0.7)",
      fontWeight: 700,
      zIndex: 3,
    },
  
    sidebar: { display: "grid", gap: 12 },
    card: {
      border: "1px solid #eee",
      borderRadius: 12,
      padding: 12,
      background: "white",
    },
    cardTitle: { fontWeight: 800, marginBottom: 8, fontSize: 13 },
    presetRow: { display: "grid", gridTemplateColumns: "1fr 34px", gap: 8, alignItems: "start" },
    presetBtn: {
      border: "1px solid #ddd",
      background: "white",
      borderRadius: 10,
      padding: 10,
      cursor: "pointer",
      textAlign: "left",
    },
    presetBtnActive: {
      border: "1px solid #111",
      background: "#f4f4f4",
      borderRadius: 10,
      padding: 10,
      cursor: "pointer",
      textAlign: "left",
    },
    iconBtn: {
      border: "1px solid #ddd",
      background: "white",
      borderRadius: 10,
      height: 40,
      cursor: "pointer",
      fontWeight: 800,
    },
    label: { display: "grid", gap: 6, fontSize: 13, fontWeight: 700, color: "#333" },
    input: {
      border: "1px solid #ddd",
      borderRadius: 10,
      padding: "10px 12px",
      fontSize: 13,
    },
  };